- name : variables
  hosts : local
  connection : local
  vars :
    COURSE : AWS with Devops
    TRAINER : Matti SivaKumar Reddy
    DURATION : 120H
    TIMMING : 7:15AM-8:45AM
  tasks :
  - name : print the variables
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}, Timming is {{TIMMING}}"
