- name : variables
  hosts : local
  connection : local
  vars : # play level variables
    COURSE : AWS with Devops
    TRAINER : Matti SivaKumar Reddy
    DURATION : 120H
    TIMMING : 7:15AM-8:45AM
  tasks :
  - name : print the variables
    vars : # task level variables
      COURSE : Ansible
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}, Timming is {{TIMMING}}"
    
  - name : print the variables1
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}, Timming is {{TIMMING}}"

