- name : variables from files
  hosts : local
  connection : local
  vars_files : 
  - vars.yaml
  tasks:
  - name : print the variables information
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}, Timming is {{TIMMING}}"

