- name : varibles from files
  hosts : local
  connection : local

  tasks :
  - name : print the variable information
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"
