- name: filter
  hosts: web
  connection: local
  tasks:
  - name: print the name is upper case
    ansible.builtin.debug:
      msg: "{{ 'srikanth' | upper }}"

  - name : converting string into list
    vars:
      fruits: "Apple, banana, cherry, mango, lemon"
    ansible.builtin.debug:
      msg: "fruits are : {{ fruits | split(',') }}"


  - name: converting dict into list
    vars:
      course:
        name: devops
        duration: 120 hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course information : {{ course | dict2items }}"

  - name: converting dict into list
    vars:
      tags:
        application: payment
        environment: dev
    ansible.builtin.debug:
      msg: "tags are : {{ tags | dict2items }}"
    

