- name: filter
  hosts: web
  connection: local
  tasks:
  - name: print the name is upper case
    ansible.builtin.debug:
      msg: "{{ 'srikanth' | upper }}"

  - name : converting string into list
    vars:
      fruits: "Apple, banana, cherry, mango, lemon"
    ansible.builtin.debug:
      msg: "fruits are : {{ fruits | split(',') }}"


  - name: converting dict into list
    vars:
      course:
        name: devops
        duration: 120 hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course information : {{ course | dict2items }}"

  - name: converting dict into list
    vars:
      tags_name:
        application: payment
        environment: dev
    ansible.builtin.debug:
      msg: "tags are : {{ tags_name | dict2items }}"

  - name: converting dict into list
    vars:
      files:
        users: /etc/passwd
        path: /etc/group
    ansible.builtin.debug:
      msg: "files are : {{ files | dict2items(key_name='file', value_name='path')}}"

  - name: converting list into dict
    vars:
      course:
      - { 'key': 'name', 'value': 'devops'}
      - {'key': 'duration', 'value': '120 hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info :{{ course | items2dict }}"
    
    

